#
# Copyright © 2025 pyjamabrah.com. All Rights Reserved.
# Author: Piyush Itankar <piyush@pyjamabrah.com>
#
RUN sudo apt-get update && \
    sudo apt-get install --no-install-recommends -y \
    sudo \
    binutils \
    make \
    git-core \
    wget \
    tree \
    build-essential \
    python3 \
    python3-dev \
    python3-pip \
    qemu-system-arm \
    gcc-arm-none-eabi \
    gdb-multiarch \
    libnewlib-arm-none-eabi
FROM pyjamabrah/sandbox:latest
